default:
  tags:
    - shared-runner:nfs


# Components to include
include:
  - component: $CI_SERVER_HOST/habitat/ci-components/wak-components/deploy@1
    inputs:
      job-name: full_build_test
  - component: $CI_SERVER_HOST/habitat/ci-components/wak-components/release_from_tag@1
    inputs:
      wak-tag-prefix: weta/
  - component: $CI_SERVER_HOST/habitat/ci-components/wak-components/deploy_custom_version@1
    inputs:
      wak-tag-prefix: weta/


stages:
  # Component specific stages
  - build
  - release

# Update the rules for the build to trigger on MR instead of branch
full_build_test:
  only:
    - merge_requests 
