default:
  tags:
    - shared-runner:nfs

# bump CI machine resources since the defaults were timing out after 1hr but the build runs in <6mins locally.
# Defaults are KUBERNETES_CPU_LIMIT="2" and KUBERNETES_MEMORY_REQUEST="1Gi"
variables:
  KUBERNETES_CPU_LIMIT: "4"
  KUBERNETES_MEMORY_REQUEST: "2Gi"

# Components to include
include:
  - component: $CI_SERVER_HOST/habitat/ci-components/wak-components/deploy@1
    inputs:
      job-name: full_build_test
  - component: $CI_SERVER_HOST/habitat/ci-components/wak-components/release_from_tag@1
    inputs:
      wak-tag-prefix: weta/
  - component: $CI_SERVER_HOST/habitat/ci-components/wak-components/deploy_custom_version@1
    inputs:
      wak-tag-prefix: weta/


stages:
  # Component specific stages
  - build
  - release

# Update the rules for the build to trigger on MR instead of branch
full_build_test:
  only:
    - merge_requests 
